section_items_dict = {'overview':{'menu_text':'Przegląd','feature_name':'overview','dppc_additional_filters_1':False,'dppc_additional_filters_2':False,'dppc_do_sorting':False,'dppc_convert_to_string':False},
                      'offer-from':{'menu_text':'Oferent','feature_name':'offer_from','dppc_additional_filters_1':False,'dppc_additional_filters_2':False,'dppc_do_sorting':False,'dppc_convert_to_string':False},
                      'version':{'menu_text':'Wersja','feature_name':'version','dppc_additional_filters_1':False,'dppc_additional_filters_2':False,'dppc_do_sorting':False,'dppc_convert_to_string':False},
                      'prod-year':{'menu_text':'Rok produkcji','feature_name':'prod_year','dppc_additional_filters_1':False,'dppc_additional_filters_2':False,'dppc_do_sorting':False,'dppc_convert_to_string':False},
                      'engine-capacity-rounded':{'menu_text':'Pojemność silnika','feature_name':'engine_capacity_rounded','dppc_additional_filters_1':True,'dppc_additional_filters_2':True,'dppc_do_sorting':True,'dppc_convert_to_string':True},
                      'engine-power':{'menu_text':'Moc silnika','feature_name':'engine_power','dppc_additional_filters_1':True,'dppc_additional_filters_2':True,'dppc_do_sorting':True,'dppc_convert_to_string':True},
                      'fuel-type':{'menu_text':'Typ paliwa','feature_name':'fuel_type','dppc_additional_filters_1':False,'dppc_additional_filters_2':False,'dppc_do_sorting':False,'dppc_convert_to_string':False},
                      'gearbox':{'menu_text':'Skrzynia biegów','feature_name':'gearbox','dppc_additional_filters_1':False,'dppc_additional_filters_2':True,'dppc_do_sorting':True,'dppc_convert_to_string':False},
                      'transmission-group':{'menu_text':'Napęd','feature_name':'transmission_group','dppc_additional_filters_1':False,'dppc_additional_filters_2':False,'dppc_do_sorting':True,'dppc_convert_to_string':False},
                      'body-type':{'menu_text':'Nadwozie','feature_name':'body_type','dppc_additional_filters_1':False,'dppc_additional_filters_2':True,'dppc_do_sorting':True,'dppc_convert_to_string':False},
                      'color':{'menu_text':'Kolor','feature_name':'color','dppc_additional_filters_1':False,'dppc_additional_filters_2':False,'dppc_do_sorting':True,'dppc_convert_to_string':False},
                      'country-of-origin':{'menu_text':'Kraj pochodzenia','feature_name':'country_of_origin','dppc_additional_filters_1':False,'dppc_additional_filters_2':True,'dppc_do_sorting':True,'dppc_convert_to_string':False},
                      'n-params-available':{'menu_text':'Liczba parametrów','feature_name':'n_params_available','dppc_additional_filters_1':False,'dppc_additional_filters_2':True,'dppc_do_sorting':False,'dppc_convert_to_string':True},
                      'n-features':{'menu_text':'Wyposażenie dodatkowe','feature_name':'n_features','dppc_additional_filters_1':False,'dppc_additional_filters_2':True,'dppc_do_sorting':False,'dppc_convert_to_string':True},
                      'mileage':{'menu_text':'Przebieg','feature_name':'mileage','dppc_additional_filters_1':False,'dppc_additional_filters_2':False,'dppc_do_sorting':False,'dppc_convert_to_string':False},
                      'price-value-pln-brutto':{'menu_text':'Cena','feature_name':'price_value_pln_brutto','dppc_additional_filters_1':False,'dppc_additional_filters_2':False,'dppc_do_sorting':False,'dppc_convert_to_string':False},

              }
